DROP DATABASE IF EXISTS PolygonDB;
Create DATABASE PolygonDB;
use PolygonDB;

CREATE TABLE zipcodes (
        zip     varchar(4),
        city    VARCHAR(25),        
primary key (zip));

CREATE TABLE customers (
        cID INT NOT NULL,
        cName VARCHAR(25) NOT NULL,
        cPhone INT(8),
        cAddress VARCHAR(25),
        zip varchar(4),
        cPassword VARCHAR (15),
primary key (cID),
foreign key(zip) references zipcodes(zip));

CREATE TABLE buildings	(
        bID INT NOT NULL auto_increment,
        cID INT not null,
        bName VARCHAR(20) NOT NULL,
    	bAddress VARCHAR(25) NOT NULL,
        zip varchar(4) NOT NULL,
    	bParcel INT NOT NULL,        
    	bSize INT NOT NULL,
        bFloors INT DEFAULT NULL,
        bStatus int(1) DEFAULT NULL,
        bYear YEAR NOT NULL,
primary key (bID),
foreign key (cID) references customers(cID), 
foreign key(zip) references zipcodes(zip));
alter table buildings auto_increment=1000;

CREATE TABLE polygonEmployee (
	pID INT NOT NULL auto_increment,
        pName VARCHAR (25),
primary key(pID));
alter table polygonEmployee auto_increment=100;

CREATE TABLE reportINFO (
    reportID INT NOT NULL,
    reportDate DATE,
    cName VARCHAR (25),
    pID INT,
    bID INT,
    bResponsible varchar(25),
primary key (reportID),
foreign key (bID) references buildings(bID), 
foreign key(pID) references polygonEmployee(pID));

CREATE TABLE buildingFloor (
    bID INT NOT NULL,
    fNo INT DEFAULT NULL,
    fSize INT DEFAULT NULL,
foreign key (bID) references buildings(bID));

CREATE TABLE room (
    roomID INT NOT NULL,
    roomName VARCHAR(25),
    roomComment VARCHAR (50),
    rRecommendation VARCHAR (50),
primary key (roomID));

CREATE TABLE moistureAnalysis (
    roomID INT NOT NULL,
    moistureScan BOOLEAN DEFAULT NULL,
    analysisResult DOUBLE DEFAULT NULL,
    analysisComment VARCHAR (50) default null,
foreign key (roomID) references room(roomID));    

CREATE TABLE damageRepair (
    roomID INT NOT NULL,
    damaged boolean default null,
    dmgDate DATE,
    dmgLocation VARCHAR (20),
    dmgDone VARCHAR (50),
    dmgRepaired VARCHAR (50),
foreign key(roomID) references room(roomID));

CREATE TABLE damageType (
    moisture_water	BOOLEAN DEFAULT NULL,
    rot_fungus	BOOLEAN DEFAULT NULL,
    mould	BOOLEAN DEFAULT NULL,
    fire	BOOLEAN DEFAULT NULL,
    otherDamage	BOOLEAN DEFAULT NULL);
    
CREATE TABLE pictures (
	bID INT NOT NULL,
    bOutside MEDIUMBLOB,
    roof MEDIUMBLOB,
    outerWalls MEDIUMBLOB,
    walls MEDIUMBLOB,
    celing MEDIUMBLOB,
	floor MEDIUMBLOB,
    windows_doors MEDIUMBLOB,
foreign key (bID) references buildings(bID));

create table floor_plan(
    bID int not null,
    floor_plan MEDIUMBLOB,
foreign key (bID) references buildings(bID));

CREATE TABLE comments (
	bID INT NOT NULL,
    bOutsideC VARCHAR (50),
    roofC VARCHAR (50),
    outerWallsC VARCHAR (50),
    wallsC VARCHAR (50),
    celingC VARCHAR (50),
	floorC VARCHAR (50),
    windows_doorsC VARCHAR (50),
foreign key(bID) references buildings(bID));    

INSERT INTO zipcodes VALUES ('0800', 'Høje Taastrup');
INSERT INTO zipcodes VALUES ('0877', 'Valby');
INSERT INTO zipcodes VALUES ('0900', 'København C');
INSERT INTO zipcodes VALUES ('0910', 'København C');
INSERT INTO zipcodes VALUES ('0929', 'København C');
INSERT INTO zipcodes VALUES ('1000', 'København K');
INSERT INTO zipcodes VALUES ('1001', 'København K');
INSERT INTO zipcodes VALUES ('1002', 'København K');
INSERT INTO zipcodes VALUES ('1003', 'København K');
INSERT INTO zipcodes VALUES ('1004', 'København K');
INSERT INTO zipcodes VALUES ('1005', 'København K');
INSERT INTO zipcodes VALUES ('1006', 'København K');
INSERT INTO zipcodes VALUES ('1007', 'København K');
INSERT INTO zipcodes VALUES ('1008', 'København K');
INSERT INTO zipcodes VALUES ('1009', 'København K');
INSERT INTO zipcodes VALUES ('1010', 'København K');
INSERT INTO zipcodes VALUES ('1011', 'København K');
INSERT INTO zipcodes VALUES ('1012', 'København K');
INSERT INTO zipcodes VALUES ('1013', 'København K');
INSERT INTO zipcodes VALUES ('1014', 'København K');
INSERT INTO zipcodes VALUES ('1015', 'København K');
INSERT INTO zipcodes VALUES ('1016', 'København K');
INSERT INTO zipcodes VALUES ('1017', 'København K');
INSERT INTO zipcodes VALUES ('1018', 'København K');
INSERT INTO zipcodes VALUES ('1019', 'København K');
INSERT INTO zipcodes VALUES ('1020', 'København K');
INSERT INTO zipcodes VALUES ('1021', 'København K');
INSERT INTO zipcodes VALUES ('1022', 'København K');
INSERT INTO zipcodes VALUES ('1023', 'København K');
INSERT INTO zipcodes VALUES ('1024', 'København K');
INSERT INTO zipcodes VALUES ('1025', 'København K');
INSERT INTO zipcodes VALUES ('1026', 'København K');
INSERT INTO zipcodes VALUES ('1045', 'København K');
INSERT INTO zipcodes VALUES ('1050', 'København K');
INSERT INTO zipcodes VALUES ('1051', 'København K');
INSERT INTO zipcodes VALUES ('1052', 'København K');
INSERT INTO zipcodes VALUES ('1053', 'København K');
INSERT INTO zipcodes VALUES ('1054', 'København K');
INSERT INTO zipcodes VALUES ('1055', 'København K');
INSERT INTO zipcodes VALUES ('1056', 'København K');
INSERT INTO zipcodes VALUES ('1057', 'København K');
INSERT INTO zipcodes VALUES ('1058', 'København K');
INSERT INTO zipcodes VALUES ('1059', 'København K');
INSERT INTO zipcodes VALUES ('1060', 'København K');
INSERT INTO zipcodes VALUES ('1061', 'København K');
INSERT INTO zipcodes VALUES ('1062', 'København K');
INSERT INTO zipcodes VALUES ('1063', 'København K');
INSERT INTO zipcodes VALUES ('1064', 'København K');
INSERT INTO zipcodes VALUES ('1065', 'København K');
INSERT INTO zipcodes VALUES ('1066', 'København K');
INSERT INTO zipcodes VALUES ('1067', 'København K');
INSERT INTO zipcodes VALUES ('1068', 'København K');
INSERT INTO zipcodes VALUES ('1069', 'København K');
INSERT INTO zipcodes VALUES ('1070', 'København K');
INSERT INTO zipcodes VALUES ('1071', 'København K');
INSERT INTO zipcodes VALUES ('1072', 'København K');
INSERT INTO zipcodes VALUES ('1073', 'København K');
INSERT INTO zipcodes VALUES ('1074', 'København K');
INSERT INTO zipcodes VALUES ('1092', 'København K');
INSERT INTO zipcodes VALUES ('1093', 'København K');
INSERT INTO zipcodes VALUES ('1095', 'København K');
INSERT INTO zipcodes VALUES ('1098', 'København K');
INSERT INTO zipcodes VALUES ('1100', 'København K');
INSERT INTO zipcodes VALUES ('1101', 'København K');
INSERT INTO zipcodes VALUES ('1102', 'København K');
INSERT INTO zipcodes VALUES ('1103', 'København K');
INSERT INTO zipcodes VALUES ('1104', 'København K');
INSERT INTO zipcodes VALUES ('1105', 'København K');
INSERT INTO zipcodes VALUES ('1106', 'København K');
INSERT INTO zipcodes VALUES ('1107', 'København K');
INSERT INTO zipcodes VALUES ('1110', 'København K');
INSERT INTO zipcodes VALUES ('1111', 'København K');
INSERT INTO zipcodes VALUES ('1112', 'København K');
INSERT INTO zipcodes VALUES ('1113', 'København K');
INSERT INTO zipcodes VALUES ('1114', 'København K');
INSERT INTO zipcodes VALUES ('1115', 'København K');
INSERT INTO zipcodes VALUES ('1116', 'København K');
INSERT INTO zipcodes VALUES ('1117', 'København K');
INSERT INTO zipcodes VALUES ('1118', 'København K');
INSERT INTO zipcodes VALUES ('1119', 'København K');
INSERT INTO zipcodes VALUES ('1120', 'København K');
INSERT INTO zipcodes VALUES ('1121', 'København K');
INSERT INTO zipcodes VALUES ('1122', 'København K');
INSERT INTO zipcodes VALUES ('1123', 'København K');
INSERT INTO zipcodes VALUES ('1124', 'København K');
INSERT INTO zipcodes VALUES ('1125', 'København K');
INSERT INTO zipcodes VALUES ('1126', 'København K');
INSERT INTO zipcodes VALUES ('1127', 'København K');
INSERT INTO zipcodes VALUES ('1128', 'København K');
INSERT INTO zipcodes VALUES ('1129', 'København K');
INSERT INTO zipcodes VALUES ('1130', 'København K');
INSERT INTO zipcodes VALUES ('1131', 'København K');
INSERT INTO zipcodes VALUES ('1140', 'København K');
INSERT INTO zipcodes VALUES ('1147', 'København K');
INSERT INTO zipcodes VALUES ('1148', 'København K');
INSERT INTO zipcodes VALUES ('1150', 'København K');
INSERT INTO zipcodes VALUES ('1151', 'København K');
INSERT INTO zipcodes VALUES ('1152', 'København K');
INSERT INTO zipcodes VALUES ('1153', 'København K');
INSERT INTO zipcodes VALUES ('1154', 'København K');
INSERT INTO zipcodes VALUES ('1155', 'København K');
INSERT INTO zipcodes VALUES ('1156', 'København K');
INSERT INTO zipcodes VALUES ('1157', 'København K');
INSERT INTO zipcodes VALUES ('1158', 'København K');
INSERT INTO zipcodes VALUES ('1159', 'København K');
INSERT INTO zipcodes VALUES ('1160', 'København K');
INSERT INTO zipcodes VALUES ('1161', 'København K');
INSERT INTO zipcodes VALUES ('1162', 'København K');
INSERT INTO zipcodes VALUES ('1163', 'København K');
INSERT INTO zipcodes VALUES ('1164', 'København K');
INSERT INTO zipcodes VALUES ('1165', 'København K');
INSERT INTO zipcodes VALUES ('1166', 'København K');
INSERT INTO zipcodes VALUES ('1167', 'København K');
INSERT INTO zipcodes VALUES ('1168', 'København K');
INSERT INTO zipcodes VALUES ('1169', 'København K');
INSERT INTO zipcodes VALUES ('1170', 'København K');
INSERT INTO zipcodes VALUES ('1171', 'København K');
INSERT INTO zipcodes VALUES ('1172', 'København K');
INSERT INTO zipcodes VALUES ('1173', 'København K');
INSERT INTO zipcodes VALUES ('1174', 'København K');
INSERT INTO zipcodes VALUES ('1175', 'København K');
INSERT INTO zipcodes VALUES ('1200', 'København K');
INSERT INTO zipcodes VALUES ('1201', 'København K');
INSERT INTO zipcodes VALUES ('1202', 'København K');
INSERT INTO zipcodes VALUES ('1203', 'København K');
INSERT INTO zipcodes VALUES ('1204', 'København K');
INSERT INTO zipcodes VALUES ('1205', 'København K');
INSERT INTO zipcodes VALUES ('1206', 'København K');
INSERT INTO zipcodes VALUES ('1207', 'København K');
INSERT INTO zipcodes VALUES ('1208', 'København K');
INSERT INTO zipcodes VALUES ('1209', 'København K');
INSERT INTO zipcodes VALUES ('1210', 'København K');
INSERT INTO zipcodes VALUES ('1211', 'København K');
INSERT INTO zipcodes VALUES ('1212', 'København K');
INSERT INTO zipcodes VALUES ('1213', 'København K');
INSERT INTO zipcodes VALUES ('1214', 'København K');
INSERT INTO zipcodes VALUES ('1215', 'København K');
INSERT INTO zipcodes VALUES ('1216', 'København K');
INSERT INTO zipcodes VALUES ('1217', 'København K');
INSERT INTO zipcodes VALUES ('1218', 'København K');
INSERT INTO zipcodes VALUES ('1219', 'København K');
INSERT INTO zipcodes VALUES ('1220', 'København K');
INSERT INTO zipcodes VALUES ('1240', 'København K');
INSERT INTO zipcodes VALUES ('1250', 'København K');
INSERT INTO zipcodes VALUES ('1251', 'København K');
INSERT INTO zipcodes VALUES ('1252', 'København K');
INSERT INTO zipcodes VALUES ('1253', 'København K');
INSERT INTO zipcodes VALUES ('1254', 'København K');
INSERT INTO zipcodes VALUES ('1255', 'København K');
INSERT INTO zipcodes VALUES ('1256', 'København K');
INSERT INTO zipcodes VALUES ('1257', 'København K');
INSERT INTO zipcodes VALUES ('1258', 'København K');
INSERT INTO zipcodes VALUES ('1259', 'København K');
INSERT INTO zipcodes VALUES ('1260', 'København K');
INSERT INTO zipcodes VALUES ('1261', 'København K');
INSERT INTO zipcodes VALUES ('1263', 'København K');
INSERT INTO zipcodes VALUES ('1264', 'København K');
INSERT INTO zipcodes VALUES ('1265', 'København K');
INSERT INTO zipcodes VALUES ('1266', 'København K');
INSERT INTO zipcodes VALUES ('1267', 'København K');
INSERT INTO zipcodes VALUES ('1268', 'København K');
INSERT INTO zipcodes VALUES ('1270', 'København K');
INSERT INTO zipcodes VALUES ('1271', 'København K');
INSERT INTO zipcodes VALUES ('1291', 'København K');
INSERT INTO zipcodes VALUES ('1300', 'København K');
INSERT INTO zipcodes VALUES ('1301', 'København K');
INSERT INTO zipcodes VALUES ('1302', 'København K');
INSERT INTO zipcodes VALUES ('1303', 'København K');
INSERT INTO zipcodes VALUES ('1304', 'København K');
INSERT INTO zipcodes VALUES ('1306', 'København K');
INSERT INTO zipcodes VALUES ('1307', 'København K');
INSERT INTO zipcodes VALUES ('1308', 'København K');
INSERT INTO zipcodes VALUES ('1309', 'København K');
INSERT INTO zipcodes VALUES ('1310', 'København K');
INSERT INTO zipcodes VALUES ('1311', 'København K');
INSERT INTO zipcodes VALUES ('1312', 'København K');
INSERT INTO zipcodes VALUES ('1313', 'København K');
INSERT INTO zipcodes VALUES ('1314', 'København K');
INSERT INTO zipcodes VALUES ('1315', 'København K');
INSERT INTO zipcodes VALUES ('1316', 'København K');
INSERT INTO zipcodes VALUES ('1317', 'København K');
INSERT INTO zipcodes VALUES ('1318', 'København K');
INSERT INTO zipcodes VALUES ('1319', 'København K');
INSERT INTO zipcodes VALUES ('1320', 'København K');
INSERT INTO zipcodes VALUES ('1321', 'København K');
INSERT INTO zipcodes VALUES ('1322', 'København K');
INSERT INTO zipcodes VALUES ('1323', 'København K');
INSERT INTO zipcodes VALUES ('1324', 'København K');
INSERT INTO zipcodes VALUES ('1325', 'København K');
INSERT INTO zipcodes VALUES ('1326', 'København K');
INSERT INTO zipcodes VALUES ('1327', 'København K');
INSERT INTO zipcodes VALUES ('1328', 'København K');
INSERT INTO zipcodes VALUES ('1329', 'København K');
INSERT INTO zipcodes VALUES ('1349', 'København K');
INSERT INTO zipcodes VALUES ('1350', 'København K');
INSERT INTO zipcodes VALUES ('1352', 'København K');
INSERT INTO zipcodes VALUES ('1353', 'København K');
INSERT INTO zipcodes VALUES ('1354', 'København K');
INSERT INTO zipcodes VALUES ('1355', 'København K');
INSERT INTO zipcodes VALUES ('1356', 'København K');
INSERT INTO zipcodes VALUES ('1357', 'København K');
INSERT INTO zipcodes VALUES ('1358', 'København K');
INSERT INTO zipcodes VALUES ('1359', 'København K');
INSERT INTO zipcodes VALUES ('1360', 'København K');
INSERT INTO zipcodes VALUES ('1361', 'København K');
INSERT INTO zipcodes VALUES ('1362', 'København K');
INSERT INTO zipcodes VALUES ('1363', 'København K');
INSERT INTO zipcodes VALUES ('1364', 'København K');
INSERT INTO zipcodes VALUES ('1365', 'København K');
INSERT INTO zipcodes VALUES ('1366', 'København K');
INSERT INTO zipcodes VALUES ('1367', 'København K');
INSERT INTO zipcodes VALUES ('1368', 'København K');
INSERT INTO zipcodes VALUES ('1369', 'København K');
INSERT INTO zipcodes VALUES ('1370', 'København K');
INSERT INTO zipcodes VALUES ('1371', 'København K');
INSERT INTO zipcodes VALUES ('1390', 'København K');
INSERT INTO zipcodes VALUES ('1399', 'København K');
INSERT INTO zipcodes VALUES ('1400', 'København K');
INSERT INTO zipcodes VALUES ('1401', 'København K');
INSERT INTO zipcodes VALUES ('1402', 'København K');
INSERT INTO zipcodes VALUES ('1403', 'København K');
INSERT INTO zipcodes VALUES ('1404', 'København K');
INSERT INTO zipcodes VALUES ('1405', 'København K');
INSERT INTO zipcodes VALUES ('1406', 'København K');
INSERT INTO zipcodes VALUES ('1407', 'København K');
INSERT INTO zipcodes VALUES ('1408', 'København K');
INSERT INTO zipcodes VALUES ('1409', 'København K');
INSERT INTO zipcodes VALUES ('1410', 'København K');
INSERT INTO zipcodes VALUES ('1411', 'København K');
INSERT INTO zipcodes VALUES ('1412', 'København K');
INSERT INTO zipcodes VALUES ('1413', 'København K');
INSERT INTO zipcodes VALUES ('1414', 'København K');
INSERT INTO zipcodes VALUES ('1415', 'København K');
INSERT INTO zipcodes VALUES ('1416', 'København K');
INSERT INTO zipcodes VALUES ('1417', 'København K');
INSERT INTO zipcodes VALUES ('1418', 'København K');
INSERT INTO zipcodes VALUES ('1419', 'København K');
INSERT INTO zipcodes VALUES ('1420', 'København K');
INSERT INTO zipcodes VALUES ('1421', 'København K');
INSERT INTO zipcodes VALUES ('1422', 'København K');
INSERT INTO zipcodes VALUES ('1423', 'København K');
INSERT INTO zipcodes VALUES ('1424', 'København K');
INSERT INTO zipcodes VALUES ('1425', 'København K');
INSERT INTO zipcodes VALUES ('1426', 'København K');
INSERT INTO zipcodes VALUES ('1427', 'København K');
INSERT INTO zipcodes VALUES ('1428', 'København K');
INSERT INTO zipcodes VALUES ('1429', 'København K');
INSERT INTO zipcodes VALUES ('1430', 'København K');
INSERT INTO zipcodes VALUES ('1431', 'København K');
INSERT INTO zipcodes VALUES ('1432', 'København K');
INSERT INTO zipcodes VALUES ('1433', 'København K');
INSERT INTO zipcodes VALUES ('1434', 'København K');
INSERT INTO zipcodes VALUES ('1435', 'København K');
INSERT INTO zipcodes VALUES ('1436', 'København K');
INSERT INTO zipcodes VALUES ('1437', 'København K');
INSERT INTO zipcodes VALUES ('1438', 'København K');
INSERT INTO zipcodes VALUES ('1439', 'København K');
INSERT INTO zipcodes VALUES ('1440', 'København K');
INSERT INTO zipcodes VALUES ('1441', 'København K');
INSERT INTO zipcodes VALUES ('1448', 'København K');
INSERT INTO zipcodes VALUES ('1450', 'København K');
INSERT INTO zipcodes VALUES ('1451', 'København K');
INSERT INTO zipcodes VALUES ('1452', 'København K');
INSERT INTO zipcodes VALUES ('1453', 'København K');
INSERT INTO zipcodes VALUES ('1454', 'København K');
INSERT INTO zipcodes VALUES ('1455', 'København K');
INSERT INTO zipcodes VALUES ('1456', 'København K');
INSERT INTO zipcodes VALUES ('1457', 'København K');
INSERT INTO zipcodes VALUES ('1458', 'København K');
INSERT INTO zipcodes VALUES ('1459', 'København K');
INSERT INTO zipcodes VALUES ('1460', 'København K');
INSERT INTO zipcodes VALUES ('1461', 'København K');
INSERT INTO zipcodes VALUES ('1462', 'København K');
INSERT INTO zipcodes VALUES ('1463', 'København K');
INSERT INTO zipcodes VALUES ('1464', 'København K');
INSERT INTO zipcodes VALUES ('1465', 'København K');
INSERT INTO zipcodes VALUES ('1466', 'København K');
INSERT INTO zipcodes VALUES ('1467', 'København K');
INSERT INTO zipcodes VALUES ('1468', 'København K');
INSERT INTO zipcodes VALUES ('1470', 'København K');
INSERT INTO zipcodes VALUES ('1471', 'København K');
INSERT INTO zipcodes VALUES ('1472', 'København K');
INSERT INTO zipcodes VALUES ('1473', 'København K');
INSERT INTO zipcodes VALUES ('1500', 'København V');
INSERT INTO zipcodes VALUES ('1501', 'København V');
INSERT INTO zipcodes VALUES ('1502', 'København V');
INSERT INTO zipcodes VALUES ('1503', 'København V');
INSERT INTO zipcodes VALUES ('1504', 'København V');
INSERT INTO zipcodes VALUES ('1505', 'København V');
INSERT INTO zipcodes VALUES ('1506', 'København V');
INSERT INTO zipcodes VALUES ('1507', 'København V');
INSERT INTO zipcodes VALUES ('1508', 'København V');
INSERT INTO zipcodes VALUES ('1509', 'København V');
INSERT INTO zipcodes VALUES ('1510', 'København V');
INSERT INTO zipcodes VALUES ('1532', 'København V');
INSERT INTO zipcodes VALUES ('1533', 'København V');
INSERT INTO zipcodes VALUES ('1550', 'København V');
INSERT INTO zipcodes VALUES ('1551', 'København V');
INSERT INTO zipcodes VALUES ('1552', 'København V');
INSERT INTO zipcodes VALUES ('1553', 'København V');
INSERT INTO zipcodes VALUES ('1554', 'København V');
INSERT INTO zipcodes VALUES ('1555', 'København V');
INSERT INTO zipcodes VALUES ('1556', 'København V');
INSERT INTO zipcodes VALUES ('1557', 'København V');
INSERT INTO zipcodes VALUES ('1558', 'København V');
INSERT INTO zipcodes VALUES ('1559', 'København V');
INSERT INTO zipcodes VALUES ('1560', 'København V');
INSERT INTO zipcodes VALUES ('1561', 'København V');
INSERT INTO zipcodes VALUES ('1562', 'København V');
INSERT INTO zipcodes VALUES ('1563', 'København V');
INSERT INTO zipcodes VALUES ('1564', 'København V');
INSERT INTO zipcodes VALUES ('1566', 'København V');
INSERT INTO zipcodes VALUES ('1567', 'København V');
INSERT INTO zipcodes VALUES ('1568', 'København V');
INSERT INTO zipcodes VALUES ('1569', 'København V');
INSERT INTO zipcodes VALUES ('1570', 'København V');
INSERT INTO zipcodes VALUES ('1571', 'København V');
INSERT INTO zipcodes VALUES ('1572', 'København V');
INSERT INTO zipcodes VALUES ('1573', 'København V');
INSERT INTO zipcodes VALUES ('1574', 'København V');
INSERT INTO zipcodes VALUES ('1575', 'København V');
INSERT INTO zipcodes VALUES ('1576', 'København V');
INSERT INTO zipcodes VALUES ('1577', 'København V');
INSERT INTO zipcodes VALUES ('1590', 'København V');
INSERT INTO zipcodes VALUES ('1592', 'København V');
INSERT INTO zipcodes VALUES ('1595', 'København V');
INSERT INTO zipcodes VALUES ('1599', 'København V');
INSERT INTO zipcodes VALUES ('1600', 'København V');
INSERT INTO zipcodes VALUES ('1601', 'København V');
INSERT INTO zipcodes VALUES ('1602', 'København V');
INSERT INTO zipcodes VALUES ('1603', 'København V');
INSERT INTO zipcodes VALUES ('1604', 'København V');
INSERT INTO zipcodes VALUES ('1605', 'København V');
INSERT INTO zipcodes VALUES ('1606', 'København V');
INSERT INTO zipcodes VALUES ('1607', 'København V');
INSERT INTO zipcodes VALUES ('1608', 'København V');
INSERT INTO zipcodes VALUES ('1609', 'København V');
INSERT INTO zipcodes VALUES ('1610', 'København V');
INSERT INTO zipcodes VALUES ('1611', 'København V');
INSERT INTO zipcodes VALUES ('1612', 'København V');
INSERT INTO zipcodes VALUES ('1613', 'København V');
INSERT INTO zipcodes VALUES ('1614', 'København V');
INSERT INTO zipcodes VALUES ('1615', 'København V');
INSERT INTO zipcodes VALUES ('1616', 'København V');
INSERT INTO zipcodes VALUES ('1617', 'København V');
INSERT INTO zipcodes VALUES ('1618', 'København V');
INSERT INTO zipcodes VALUES ('1619', 'København V');
INSERT INTO zipcodes VALUES ('1620', 'København V');
INSERT INTO zipcodes VALUES ('1621', 'København V');
INSERT INTO zipcodes VALUES ('1622', 'København V');
INSERT INTO zipcodes VALUES ('1623', 'København V');
INSERT INTO zipcodes VALUES ('1624', 'København V');
INSERT INTO zipcodes VALUES ('1630', 'København V');
INSERT INTO zipcodes VALUES ('1631', 'København V');
INSERT INTO zipcodes VALUES ('1632', 'København V');
INSERT INTO zipcodes VALUES ('1633', 'København V');
INSERT INTO zipcodes VALUES ('1634', 'København V');
INSERT INTO zipcodes VALUES ('1635', 'København V');
INSERT INTO zipcodes VALUES ('1639', 'København V');
INSERT INTO zipcodes VALUES ('1640', 'København V');
INSERT INTO zipcodes VALUES ('1650', 'København V');
INSERT INTO zipcodes VALUES ('1651', 'København V');
INSERT INTO zipcodes VALUES ('1652', 'København V');
INSERT INTO zipcodes VALUES ('1653', 'København V');
INSERT INTO zipcodes VALUES ('1654', 'København V');
INSERT INTO zipcodes VALUES ('1655', 'København V');
INSERT INTO zipcodes VALUES ('1656', 'København V');
INSERT INTO zipcodes VALUES ('1657', 'København V');
INSERT INTO zipcodes VALUES ('1658', 'København V');
INSERT INTO zipcodes VALUES ('1659', 'København V');
INSERT INTO zipcodes VALUES ('1660', 'København V');
INSERT INTO zipcodes VALUES ('1661', 'København V');
INSERT INTO zipcodes VALUES ('1662', 'København V');
INSERT INTO zipcodes VALUES ('1663', 'København V');
INSERT INTO zipcodes VALUES ('1664', 'København V');
INSERT INTO zipcodes VALUES ('1665', 'København V');
INSERT INTO zipcodes VALUES ('1666', 'København V');
INSERT INTO zipcodes VALUES ('1667', 'København V');
INSERT INTO zipcodes VALUES ('1668', 'København V');
INSERT INTO zipcodes VALUES ('1669', 'København V');
INSERT INTO zipcodes VALUES ('1670', 'København V');
INSERT INTO zipcodes VALUES ('1671', 'København V');
INSERT INTO zipcodes VALUES ('1672', 'København V');
INSERT INTO zipcodes VALUES ('1673', 'København V');
INSERT INTO zipcodes VALUES ('1674', 'København V');
INSERT INTO zipcodes VALUES ('1675', 'København V');
INSERT INTO zipcodes VALUES ('1676', 'København V');
INSERT INTO zipcodes VALUES ('1677', 'København V');
INSERT INTO zipcodes VALUES ('1699', 'København V');
INSERT INTO zipcodes VALUES ('1700', 'København V');
INSERT INTO zipcodes VALUES ('1701', 'København V');
INSERT INTO zipcodes VALUES ('1702', 'København V');
INSERT INTO zipcodes VALUES ('1703', 'København V');
INSERT INTO zipcodes VALUES ('1704', 'København V');
INSERT INTO zipcodes VALUES ('1705', 'København V');
INSERT INTO zipcodes VALUES ('1706', 'København V');
INSERT INTO zipcodes VALUES ('1707', 'København V');
INSERT INTO zipcodes VALUES ('1708', 'København V');
INSERT INTO zipcodes VALUES ('1709', 'København V');
INSERT INTO zipcodes VALUES ('1710', 'København V');
INSERT INTO zipcodes VALUES ('1711', 'København V');
INSERT INTO zipcodes VALUES ('1712', 'København V');
INSERT INTO zipcodes VALUES ('1713', 'København V');
INSERT INTO zipcodes VALUES ('1714', 'København V');
INSERT INTO zipcodes VALUES ('1715', 'København V');
INSERT INTO zipcodes VALUES ('1716', 'København V');
INSERT INTO zipcodes VALUES ('1717', 'København V');
INSERT INTO zipcodes VALUES ('1718', 'København V');
INSERT INTO zipcodes VALUES ('1719', 'København V');
INSERT INTO zipcodes VALUES ('1720', 'København V');
INSERT INTO zipcodes VALUES ('1721', 'København V');
INSERT INTO zipcodes VALUES ('1722', 'København V');
INSERT INTO zipcodes VALUES ('1723', 'København V');
INSERT INTO zipcodes VALUES ('1724', 'København V');
INSERT INTO zipcodes VALUES ('1725', 'København V');
INSERT INTO zipcodes VALUES ('1726', 'København V');
INSERT INTO zipcodes VALUES ('1727', 'København V');
INSERT INTO zipcodes VALUES ('1728', 'København V');
INSERT INTO zipcodes VALUES ('1729', 'København V');
INSERT INTO zipcodes VALUES ('1730', 'København V');
INSERT INTO zipcodes VALUES ('1731', 'København V');
INSERT INTO zipcodes VALUES ('1732', 'København V');
INSERT INTO zipcodes VALUES ('1733', 'København V');
INSERT INTO zipcodes VALUES ('1734', 'København V');
INSERT INTO zipcodes VALUES ('1735', 'København V');
INSERT INTO zipcodes VALUES ('1736', 'København V');
INSERT INTO zipcodes VALUES ('1737', 'København V');
INSERT INTO zipcodes VALUES ('1738', 'København V');
INSERT INTO zipcodes VALUES ('1739', 'København V');
INSERT INTO zipcodes VALUES ('1748', 'København V');
INSERT INTO zipcodes VALUES ('1749', 'København V');
INSERT INTO zipcodes VALUES ('1750', 'København V');
INSERT INTO zipcodes VALUES ('1751', 'København V');
INSERT INTO zipcodes VALUES ('1752', 'København V');
INSERT INTO zipcodes VALUES ('1753', 'København V');
INSERT INTO zipcodes VALUES ('1754', 'København V');
INSERT INTO zipcodes VALUES ('1755', 'København V');
INSERT INTO zipcodes VALUES ('1756', 'København V');
INSERT INTO zipcodes VALUES ('1757', 'København V');
INSERT INTO zipcodes VALUES ('1758', 'København V');
INSERT INTO zipcodes VALUES ('1759', 'København V');
INSERT INTO zipcodes VALUES ('1760', 'København V');
INSERT INTO zipcodes VALUES ('1761', 'København V');
INSERT INTO zipcodes VALUES ('1762', 'København V');
INSERT INTO zipcodes VALUES ('1763', 'København V');
INSERT INTO zipcodes VALUES ('1764', 'København V');
INSERT INTO zipcodes VALUES ('1765', 'København V');
INSERT INTO zipcodes VALUES ('1766', 'København V');
INSERT INTO zipcodes VALUES ('1770', 'København V');
INSERT INTO zipcodes VALUES ('1771', 'København V');
INSERT INTO zipcodes VALUES ('1772', 'København V');
INSERT INTO zipcodes VALUES ('1773', 'København V');
INSERT INTO zipcodes VALUES ('1774', 'København V');
INSERT INTO zipcodes VALUES ('1775', 'København V');
INSERT INTO zipcodes VALUES ('1777', 'København V');
INSERT INTO zipcodes VALUES ('1778', 'København V');
INSERT INTO zipcodes VALUES ('1780', 'København V');
INSERT INTO zipcodes VALUES ('1782', 'København V');
INSERT INTO zipcodes VALUES ('1783', 'København V');
INSERT INTO zipcodes VALUES ('1784', 'København V');
INSERT INTO zipcodes VALUES ('1785', 'København V');
INSERT INTO zipcodes VALUES ('1786', 'København V');
INSERT INTO zipcodes VALUES ('1787', 'København V');
INSERT INTO zipcodes VALUES ('1788', 'København V');
INSERT INTO zipcodes VALUES ('1789', 'København V');
INSERT INTO zipcodes VALUES ('1790', 'København V');
INSERT INTO zipcodes VALUES ('1795', 'København V');
INSERT INTO zipcodes VALUES ('1799', 'København V');
INSERT INTO zipcodes VALUES ('1800', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1801', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1802', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1803', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1804', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1805', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1806', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1807', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1808', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1809', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1810', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1811', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1812', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1813', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1814', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1815', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1816', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1817', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1818', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1819', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1820', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1822', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1823', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1824', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1825', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1826', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1827', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1828', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1829', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1835', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1850', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1851', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1852', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1853', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1854', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1855', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1856', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1857', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1860', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1861', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1862', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1863', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1864', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1865', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1866', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1867', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1868', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1870', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1871', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1872', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1873', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1874', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1875', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1876', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1877', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1878', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1879', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1900', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1901', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1902', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1903', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1904', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1905', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1906', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1908', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1909', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1910', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1911', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1912', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1913', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1914', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1915', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1916', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1917', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1920', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1921', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1922', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1923', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1924', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1925', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1926', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1927', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1928', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1931', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1950', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1951', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1952', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1953', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1954', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1955', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1956', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1957', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1958', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1959', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1960', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1961', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1962', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1963', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1964', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1965', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1966', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1967', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1970', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1971', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1972', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1973', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1974', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('1999', 'Frederiksberg C');
INSERT INTO zipcodes VALUES ('2000', 'Frederiksberg');
INSERT INTO zipcodes VALUES ('2100', 'København Ø');
INSERT INTO zipcodes VALUES ('2200', 'København N');
INSERT INTO zipcodes VALUES ('2300', 'København S');
INSERT INTO zipcodes VALUES ('2400', 'København NV');
INSERT INTO zipcodes VALUES ('2450', 'København SV');
INSERT INTO zipcodes VALUES ('2500', 'Valby');
INSERT INTO zipcodes VALUES ('2600', 'Glostrup');
INSERT INTO zipcodes VALUES ('2605', 'Brøndby');
INSERT INTO zipcodes VALUES ('2610', 'Rødovre');
INSERT INTO zipcodes VALUES ('2620', 'Albertslund');
INSERT INTO zipcodes VALUES ('2625', 'Vallensbæk');
INSERT INTO zipcodes VALUES ('2630', 'Taastrup');
INSERT INTO zipcodes VALUES ('2633', 'Taastrup');
INSERT INTO zipcodes VALUES ('2635', 'Ishøj');
INSERT INTO zipcodes VALUES ('2640', 'Hedehusene');
INSERT INTO zipcodes VALUES ('2650', 'Hvidovre');
INSERT INTO zipcodes VALUES ('2660', 'Brøndby Strand');
INSERT INTO zipcodes VALUES ('2665', 'Vallensbæk Strand');
INSERT INTO zipcodes VALUES ('2670', 'Greve');
INSERT INTO zipcodes VALUES ('2680', 'Solrød Strand');
INSERT INTO zipcodes VALUES ('2690', 'Karlslunde');
INSERT INTO zipcodes VALUES ('2700', 'Brønshøj');
INSERT INTO zipcodes VALUES ('2720', 'Vanløse');
INSERT INTO zipcodes VALUES ('2730', 'Herlev');
INSERT INTO zipcodes VALUES ('2740', 'Skovlunde');
INSERT INTO zipcodes VALUES ('2750', 'Ballerup');
INSERT INTO zipcodes VALUES ('2760', 'Måløv');
INSERT INTO zipcodes VALUES ('2765', 'Smørum');
INSERT INTO zipcodes VALUES ('2770', 'Kastrup');
INSERT INTO zipcodes VALUES ('2791', 'Dragør');
INSERT INTO zipcodes VALUES ('2800', 'Kongens Lyngby');
INSERT INTO zipcodes VALUES ('2820', 'Gentofte');
INSERT INTO zipcodes VALUES ('2830', 'Virum');
INSERT INTO zipcodes VALUES ('2840', 'Holte');
INSERT INTO zipcodes VALUES ('2850', 'Nærum');
INSERT INTO zipcodes VALUES ('2860', 'Søborg');
INSERT INTO zipcodes VALUES ('2870', 'Dyssegård');
INSERT INTO zipcodes VALUES ('2880', 'Bagsværd');
INSERT INTO zipcodes VALUES ('2900', 'Hellerup');
INSERT INTO zipcodes VALUES ('2920', 'Charlottenlund');
INSERT INTO zipcodes VALUES ('2930', 'Klampenborg');
INSERT INTO zipcodes VALUES ('2942', 'Skodsborg');
INSERT INTO zipcodes VALUES ('2950', 'Vedbæk');
INSERT INTO zipcodes VALUES ('2960', 'Rungsted Kyst');
INSERT INTO zipcodes VALUES ('2970', 'Hørsholm');
INSERT INTO zipcodes VALUES ('2980', 'Kokkedal');
INSERT INTO zipcodes VALUES ('2990', 'Nivå');
INSERT INTO zipcodes VALUES ('3000', 'Helsingør');
INSERT INTO zipcodes VALUES ('3050', 'Humlebæk');
INSERT INTO zipcodes VALUES ('3060', 'Espergærde');
INSERT INTO zipcodes VALUES ('3070', 'Snekkersten');
INSERT INTO zipcodes VALUES ('3080', 'Tikøb');
INSERT INTO zipcodes VALUES ('3100', 'Hornbæk');
INSERT INTO zipcodes VALUES ('3120', 'Dronningmølle');
INSERT INTO zipcodes VALUES ('3140', 'Ålsgårde');
INSERT INTO zipcodes VALUES ('3150', 'Hellebæk');
INSERT INTO zipcodes VALUES ('3200', 'Helsinge');
INSERT INTO zipcodes VALUES ('3210', 'Vejby');
INSERT INTO zipcodes VALUES ('3220', 'Tisvildeleje');
INSERT INTO zipcodes VALUES ('3230', 'Græsted');
INSERT INTO zipcodes VALUES ('3250', 'Gilleleje');
INSERT INTO zipcodes VALUES ('3300', 'Frederiksværk');
INSERT INTO zipcodes VALUES ('3310', 'Ølsted');
INSERT INTO zipcodes VALUES ('3320', 'Skævinge');
INSERT INTO zipcodes VALUES ('3330', 'Gørløse');
INSERT INTO zipcodes VALUES ('3360', 'Liseleje');
INSERT INTO zipcodes VALUES ('3370', 'Melby');
INSERT INTO zipcodes VALUES ('3390', 'Hundested');
INSERT INTO zipcodes VALUES ('3400', 'Hillerød');
INSERT INTO zipcodes VALUES ('3450', 'Allerød');
INSERT INTO zipcodes VALUES ('3460', 'Birkerød');
INSERT INTO zipcodes VALUES ('3480', 'Fredensborg');
INSERT INTO zipcodes VALUES ('3490', 'Kvistgård');
INSERT INTO zipcodes VALUES ('3500', 'Værløse');
INSERT INTO zipcodes VALUES ('3520', 'Farum');
INSERT INTO zipcodes VALUES ('3540', 'Lynge');
INSERT INTO zipcodes VALUES ('3550', 'Slangerup');
INSERT INTO zipcodes VALUES ('3600', 'Frederikssund');
INSERT INTO zipcodes VALUES ('3630', 'Jægerspris');
INSERT INTO zipcodes VALUES ('3650', 'Ølstykke');
INSERT INTO zipcodes VALUES ('3660', 'Stenløse');
INSERT INTO zipcodes VALUES ('3670', 'Veksø Sjælland');
INSERT INTO zipcodes VALUES ('3700', 'Rønne');
INSERT INTO zipcodes VALUES ('3720', 'Aakirkeby');
INSERT INTO zipcodes VALUES ('3730', 'Nexø');
INSERT INTO zipcodes VALUES ('3740', 'Svaneke');
INSERT INTO zipcodes VALUES ('3751', 'Østermarie');
INSERT INTO zipcodes VALUES ('3760', 'Gudhjem');
INSERT INTO zipcodes VALUES ('3770', 'Allinge');
INSERT INTO zipcodes VALUES ('3782', 'Klemensker');
INSERT INTO zipcodes VALUES ('3790', 'Hasle');
INSERT INTO zipcodes VALUES ('4000', 'Roskilde');
INSERT INTO zipcodes VALUES ('4030', 'Tune');
INSERT INTO zipcodes VALUES ('4040', 'Jyllinge');
INSERT INTO zipcodes VALUES ('4050', 'Skibby');
INSERT INTO zipcodes VALUES ('4060', 'Kirke Såby');
INSERT INTO zipcodes VALUES ('4070', 'Kirke Hyllinge');
INSERT INTO zipcodes VALUES ('4100', 'Ringsted');
INSERT INTO zipcodes VALUES ('4105', 'Ringsted');
INSERT INTO zipcodes VALUES ('4129', 'Ringsted');
INSERT INTO zipcodes VALUES ('4130', 'Viby Sjælland');
INSERT INTO zipcodes VALUES ('4140', 'Borup');
INSERT INTO zipcodes VALUES ('4160', 'Herlufmagle');
INSERT INTO zipcodes VALUES ('4171', 'Glumsø');
INSERT INTO zipcodes VALUES ('4173', 'Fjenneslev');
INSERT INTO zipcodes VALUES ('4174', 'Jystrup Midtsj');
INSERT INTO zipcodes VALUES ('4180', 'Sorø');
INSERT INTO zipcodes VALUES ('4190', 'Munke Bjergby');
INSERT INTO zipcodes VALUES ('4200', 'Slagelse');
INSERT INTO zipcodes VALUES ('4220', 'Korsør');
INSERT INTO zipcodes VALUES ('4230', 'Skælskør');
INSERT INTO zipcodes VALUES ('4241', 'Vemmelev');
INSERT INTO zipcodes VALUES ('4242', 'Boeslunde');
INSERT INTO zipcodes VALUES ('4243', 'Rude');
INSERT INTO zipcodes VALUES ('4250', 'Fuglebjerg');
INSERT INTO zipcodes VALUES ('4261', 'Dalmose');
INSERT INTO zipcodes VALUES ('4262', 'Sandved');
INSERT INTO zipcodes VALUES ('4270', 'Høng');
INSERT INTO zipcodes VALUES ('4281', 'Gørlev');
INSERT INTO zipcodes VALUES ('4291', 'Ruds Vedby');
INSERT INTO zipcodes VALUES ('4293', 'Dianalund');
INSERT INTO zipcodes VALUES ('4295', 'Stenlille');
INSERT INTO zipcodes VALUES ('4296', 'Nyrup');
INSERT INTO zipcodes VALUES ('4300', 'Holbæk');
INSERT INTO zipcodes VALUES ('4320', 'Lejre');
INSERT INTO zipcodes VALUES ('4330', 'Hvalsø');
INSERT INTO zipcodes VALUES ('4340', 'Tølløse');
INSERT INTO zipcodes VALUES ('4350', 'Ugerløse');
INSERT INTO zipcodes VALUES ('4360', 'Kirke Eskilstrup');
INSERT INTO zipcodes VALUES ('4370', 'Store Merløse');
INSERT INTO zipcodes VALUES ('4390', 'Vipperød');
INSERT INTO zipcodes VALUES ('4400', 'Kalundborg');
INSERT INTO zipcodes VALUES ('4420', 'Regstrup');
INSERT INTO zipcodes VALUES ('4440', 'Mørkøv');
INSERT INTO zipcodes VALUES ('4450', 'Jyderup');
INSERT INTO zipcodes VALUES ('4460', 'Snertinge');
INSERT INTO zipcodes VALUES ('4470', 'Svebølle');
INSERT INTO zipcodes VALUES ('4480', 'Store Fuglede');
INSERT INTO zipcodes VALUES ('4490', 'Jerslev Sjælland');
INSERT INTO zipcodes VALUES ('4500', 'Nykøbing Sj');
INSERT INTO zipcodes VALUES ('4520', 'Svinninge');
INSERT INTO zipcodes VALUES ('4532', 'Gislinge');
INSERT INTO zipcodes VALUES ('4534', 'Hørve');
INSERT INTO zipcodes VALUES ('4540', 'Fårevejle');
INSERT INTO zipcodes VALUES ('4550', 'Asnæs');
INSERT INTO zipcodes VALUES ('4560', 'Vig');
INSERT INTO zipcodes VALUES ('4571', 'Grevinge');
INSERT INTO zipcodes VALUES ('4572', 'Nørre Asmindrup');
INSERT INTO zipcodes VALUES ('4573', 'Højby');
INSERT INTO zipcodes VALUES ('4581', 'Rørvig');
INSERT INTO zipcodes VALUES ('4583', 'Sjællands Odde');
INSERT INTO zipcodes VALUES ('4591', 'Føllenslev');
INSERT INTO zipcodes VALUES ('4592', 'Sejerø');
INSERT INTO zipcodes VALUES ('4593', 'Eskebjerg');
INSERT INTO zipcodes VALUES ('4600', 'Køge');
INSERT INTO zipcodes VALUES ('4621', 'Gadstrup');
INSERT INTO zipcodes VALUES ('4622', 'Havdrup');
INSERT INTO zipcodes VALUES ('4623', 'Lille Skensved');
INSERT INTO zipcodes VALUES ('4632', 'Bjæverskov');
INSERT INTO zipcodes VALUES ('4640', 'Fakse');
INSERT INTO zipcodes VALUES ('4652', 'Hårlev');
INSERT INTO zipcodes VALUES ('4653', 'Karise');
INSERT INTO zipcodes VALUES ('4654', 'Fakse Ladeplads');
INSERT INTO zipcodes VALUES ('4660', 'Store Heddinge');
INSERT INTO zipcodes VALUES ('4671', 'Strøby');
INSERT INTO zipcodes VALUES ('4672', 'Klippinge');
INSERT INTO zipcodes VALUES ('4673', 'Rødvig Stevns');
INSERT INTO zipcodes VALUES ('4681', 'Herfølge');
INSERT INTO zipcodes VALUES ('4682', 'Tureby');
INSERT INTO zipcodes VALUES ('4683', 'Rønnede');
INSERT INTO zipcodes VALUES ('4684', 'Holmegaard');
INSERT INTO zipcodes VALUES ('4690', 'Haslev');
INSERT INTO zipcodes VALUES ('4700', 'Næstved');
INSERT INTO zipcodes VALUES ('4720', 'Præstø');
INSERT INTO zipcodes VALUES ('4733', 'Tappernøje');
INSERT INTO zipcodes VALUES ('4735', 'Mern');
INSERT INTO zipcodes VALUES ('4736', 'Karrebæksminde');
INSERT INTO zipcodes VALUES ('4750', 'Lundby');
INSERT INTO zipcodes VALUES ('4760', 'Vordingborg');
INSERT INTO zipcodes VALUES ('4771', 'Kalvehave');
INSERT INTO zipcodes VALUES ('4772', 'Langebæk');
INSERT INTO zipcodes VALUES ('4773', 'Stensved');
INSERT INTO zipcodes VALUES ('4780', 'Stege');
INSERT INTO zipcodes VALUES ('4791', 'Borre');
INSERT INTO zipcodes VALUES ('4792', 'Askeby');
INSERT INTO zipcodes VALUES ('4793', 'Bogø By');
INSERT INTO zipcodes VALUES ('4800', 'Nykøbing F');
INSERT INTO zipcodes VALUES ('4840', 'Nørre Alslev');
INSERT INTO zipcodes VALUES ('4850', 'Stubbekøbing');
INSERT INTO zipcodes VALUES ('4862', 'Guldborg');
INSERT INTO zipcodes VALUES ('4863', 'Eskilstrup');
INSERT INTO zipcodes VALUES ('4871', 'Horbelev');
INSERT INTO zipcodes VALUES ('4872', 'Idestrup');
INSERT INTO zipcodes VALUES ('4873', 'Væggerløse');
INSERT INTO zipcodes VALUES ('4874', 'Gedser');
INSERT INTO zipcodes VALUES ('4880', 'Nysted');
INSERT INTO zipcodes VALUES ('4891', 'Toreby L');
INSERT INTO zipcodes VALUES ('4892', 'Kettinge');
INSERT INTO zipcodes VALUES ('4894', 'Øster Ulslev');
INSERT INTO zipcodes VALUES ('4895', 'Errindlev');
INSERT INTO zipcodes VALUES ('4900', 'Nakskov');
INSERT INTO zipcodes VALUES ('4912', 'Harpelunde');
INSERT INTO zipcodes VALUES ('4913', 'Horslunde');
INSERT INTO zipcodes VALUES ('4920', 'Søllested');
INSERT INTO zipcodes VALUES ('4930', 'Maribo');
INSERT INTO zipcodes VALUES ('4941', 'Bandholm');
INSERT INTO zipcodes VALUES ('4943', 'Torrig L');
INSERT INTO zipcodes VALUES ('4944', 'Fejø');
INSERT INTO zipcodes VALUES ('4951', 'Nørreballe');
INSERT INTO zipcodes VALUES ('4952', 'Stokkemarke');
INSERT INTO zipcodes VALUES ('4953', 'Vesterborg');
INSERT INTO zipcodes VALUES ('4960', 'Holeby');
INSERT INTO zipcodes VALUES ('4970', 'Rødby');
INSERT INTO zipcodes VALUES ('4983', 'Dannemare');
INSERT INTO zipcodes VALUES ('4990', 'Sakskøbing');
INSERT INTO zipcodes VALUES ('5000', 'Odense C');
INSERT INTO zipcodes VALUES ('5029', 'Odense C');
INSERT INTO zipcodes VALUES ('5090', 'Odense C');
INSERT INTO zipcodes VALUES ('5100', 'Odense C');
INSERT INTO zipcodes VALUES ('5200', 'Odense V');
INSERT INTO zipcodes VALUES ('5210', 'Odense NV');
INSERT INTO zipcodes VALUES ('5220', 'Odense SØ');
INSERT INTO zipcodes VALUES ('5230', 'Odense M');
INSERT INTO zipcodes VALUES ('5240', 'Odense NØ');
INSERT INTO zipcodes VALUES ('5250', 'Odense SV');
INSERT INTO zipcodes VALUES ('5260', 'Odense S');
INSERT INTO zipcodes VALUES ('5270', 'Odense N');
INSERT INTO zipcodes VALUES ('5290', 'Marslev');
INSERT INTO zipcodes VALUES ('5300', 'Kerteminde');
INSERT INTO zipcodes VALUES ('5320', 'Agedrup');
INSERT INTO zipcodes VALUES ('5330', 'Munkebo');
INSERT INTO zipcodes VALUES ('5350', 'Rynkeby');
INSERT INTO zipcodes VALUES ('5370', 'Mesinge');
INSERT INTO zipcodes VALUES ('5380', 'Dalby');
INSERT INTO zipcodes VALUES ('5390', 'Martofte');
INSERT INTO zipcodes VALUES ('5400', 'Bogense');
INSERT INTO zipcodes VALUES ('5450', 'Otterup');
INSERT INTO zipcodes VALUES ('5462', 'Morud');
INSERT INTO zipcodes VALUES ('5463', 'Harndrup');
INSERT INTO zipcodes VALUES ('5464', 'Brenderup Fyn');
INSERT INTO zipcodes VALUES ('5466', 'Asperup');
INSERT INTO zipcodes VALUES ('5471', 'Søndersø');
INSERT INTO zipcodes VALUES ('5474', 'Veflinge');
INSERT INTO zipcodes VALUES ('5485', 'Skamby');
INSERT INTO zipcodes VALUES ('5491', 'Blommenslyst');
INSERT INTO zipcodes VALUES ('5492', 'Vissenbjerg');
INSERT INTO zipcodes VALUES ('5500', 'Middelfart');
INSERT INTO zipcodes VALUES ('5540', 'Ullerslev');
INSERT INTO zipcodes VALUES ('5550', 'Langeskov');
INSERT INTO zipcodes VALUES ('5560', 'Aarup');
INSERT INTO zipcodes VALUES ('5580', 'Nørre Aaby');
INSERT INTO zipcodes VALUES ('5591', 'Gelsted');
INSERT INTO zipcodes VALUES ('5592', 'Ejby');
INSERT INTO zipcodes VALUES ('5600', 'Faaborg');
INSERT INTO zipcodes VALUES ('5610', 'Assens');
INSERT INTO zipcodes VALUES ('5620', 'Glamsbjerg');
INSERT INTO zipcodes VALUES ('5631', 'Ebberup');
INSERT INTO zipcodes VALUES ('5642', 'Millinge');
INSERT INTO zipcodes VALUES ('5672', 'Broby');
INSERT INTO zipcodes VALUES ('5683', 'Haarby');
INSERT INTO zipcodes VALUES ('5690', 'Tommerup');
INSERT INTO zipcodes VALUES ('5700', 'Svendborg');
INSERT INTO zipcodes VALUES ('5750', 'Ringe');
INSERT INTO zipcodes VALUES ('5762', 'Vester Skerninge');
INSERT INTO zipcodes VALUES ('5771', 'Stenstrup');
INSERT INTO zipcodes VALUES ('5772', 'Kværndrup');
INSERT INTO zipcodes VALUES ('5792', 'Årslev');
INSERT INTO zipcodes VALUES ('5800', 'Nyborg');
INSERT INTO zipcodes VALUES ('5853', 'Ørbæk');
INSERT INTO zipcodes VALUES ('5854', 'Gislev');
INSERT INTO zipcodes VALUES ('5856', 'Ryslinge');
INSERT INTO zipcodes VALUES ('5863', 'Ferritslev Fyn');
INSERT INTO zipcodes VALUES ('5871', 'Frørup');
INSERT INTO zipcodes VALUES ('5874', 'Hesselager');
INSERT INTO zipcodes VALUES ('5881', 'Skårup Fyn');
INSERT INTO zipcodes VALUES ('5882', 'Vejstrup');
INSERT INTO zipcodes VALUES ('5883', 'Oure');
INSERT INTO zipcodes VALUES ('5884', 'Gudme');
INSERT INTO zipcodes VALUES ('5892', 'Gudbjerg Sydfyn');
INSERT INTO zipcodes VALUES ('5900', 'Ruøbing');
INSERT INTO zipcodes VALUES ('5932', 'Humble');
INSERT INTO zipcodes VALUES ('5935', 'Bagenkop');
INSERT INTO zipcodes VALUES ('5953', 'Tranekær');
INSERT INTO zipcodes VALUES ('5960', 'Marstal');
INSERT INTO zipcodes VALUES ('5970', 'Ærøskøbing');
INSERT INTO zipcodes VALUES ('5985', 'Søby Ærø');
INSERT INTO zipcodes VALUES ('6000', 'Kolding');
INSERT INTO zipcodes VALUES ('6040', 'Egtved');
INSERT INTO zipcodes VALUES ('6051', 'Almind');
INSERT INTO zipcodes VALUES ('6052', 'Viuf');
INSERT INTO zipcodes VALUES ('6064', 'Jordrup');
INSERT INTO zipcodes VALUES ('6070', 'Christiansfeld');
INSERT INTO zipcodes VALUES ('6091', 'Bjert');
INSERT INTO zipcodes VALUES ('6092', 'Sønder Stenderup');
INSERT INTO zipcodes VALUES ('6093', 'Sjølund');
INSERT INTO zipcodes VALUES ('6094', 'Hejls');
INSERT INTO zipcodes VALUES ('6100', 'Haderslev');
INSERT INTO zipcodes VALUES ('6200', 'Aabenraa');
INSERT INTO zipcodes VALUES ('6230', 'Rødekro');
INSERT INTO zipcodes VALUES ('6240', 'Løgumkloster');
INSERT INTO zipcodes VALUES ('6261', 'Bredebro');
INSERT INTO zipcodes VALUES ('6270', 'Tønder');
INSERT INTO zipcodes VALUES ('6280', 'Højer');
INSERT INTO zipcodes VALUES ('6300', 'Gråsten');
INSERT INTO zipcodes VALUES ('6310', 'Broager');
INSERT INTO zipcodes VALUES ('6320', 'Egernsund');
INSERT INTO zipcodes VALUES ('6330', 'Padborg');
INSERT INTO zipcodes VALUES ('6340', 'Kruså');
INSERT INTO zipcodes VALUES ('6360', 'Tinglev');
INSERT INTO zipcodes VALUES ('6372', 'Bylderup-Bov');
INSERT INTO zipcodes VALUES ('6392', 'Bolderslev');
INSERT INTO zipcodes VALUES ('6400', 'Sønderborg');
INSERT INTO zipcodes VALUES ('6430', 'Nordborg');
INSERT INTO zipcodes VALUES ('6440', 'Augustenborg');
INSERT INTO zipcodes VALUES ('6470', 'Sydals');
INSERT INTO zipcodes VALUES ('6500', 'Vojens');
INSERT INTO zipcodes VALUES ('6510', 'Gram');
INSERT INTO zipcodes VALUES ('6520', 'Toftlund');
INSERT INTO zipcodes VALUES ('6534', 'Agerskov');
INSERT INTO zipcodes VALUES ('6535', 'Branderup J');
INSERT INTO zipcodes VALUES ('6541', 'Bevtoft');
INSERT INTO zipcodes VALUES ('6560', 'Sommersted');
INSERT INTO zipcodes VALUES ('6580', 'Vamdrup');
INSERT INTO zipcodes VALUES ('6600', 'Vejen');
INSERT INTO zipcodes VALUES ('6621', 'Gesten');
INSERT INTO zipcodes VALUES ('6622', 'Bække');
INSERT INTO zipcodes VALUES ('6623', 'Vorbasse');
INSERT INTO zipcodes VALUES ('6630', 'Rødding');
INSERT INTO zipcodes VALUES ('6640', 'Lunderskov');
INSERT INTO zipcodes VALUES ('6650', 'Brørup');
INSERT INTO zipcodes VALUES ('6660', 'Lintrup');
INSERT INTO zipcodes VALUES ('6670', 'Holsted');
INSERT INTO zipcodes VALUES ('6682', 'Hovborg');
INSERT INTO zipcodes VALUES ('6683', 'Føvling');
INSERT INTO zipcodes VALUES ('6690', 'Gørding');
INSERT INTO zipcodes VALUES ('6700', 'Esbjerg');
INSERT INTO zipcodes VALUES ('6701', 'Esbjerg');
INSERT INTO zipcodes VALUES ('6705', 'Esbjerg Ø');
INSERT INTO zipcodes VALUES ('6710', 'Esbjerg V');
INSERT INTO zipcodes VALUES ('6715', 'Esbjerg N');
INSERT INTO zipcodes VALUES ('6720', 'Fanø');
INSERT INTO zipcodes VALUES ('6731', 'Tjæreborg');
INSERT INTO zipcodes VALUES ('6740', 'Bramming');
INSERT INTO zipcodes VALUES ('6752', 'Glejbjerg');
INSERT INTO zipcodes VALUES ('6753', 'Agerbæk');
INSERT INTO zipcodes VALUES ('6760', 'Ribe');
INSERT INTO zipcodes VALUES ('6771', 'Gredstedbro');
INSERT INTO zipcodes VALUES ('6780', 'Skærbæk');
INSERT INTO zipcodes VALUES ('6792', 'Rømø');
INSERT INTO zipcodes VALUES ('6800', 'Varde');
INSERT INTO zipcodes VALUES ('6818', 'Årre');
INSERT INTO zipcodes VALUES ('6823', 'Ansager');
INSERT INTO zipcodes VALUES ('6830', 'Nørre Nebel');
INSERT INTO zipcodes VALUES ('6840', 'Oksbøl');
INSERT INTO zipcodes VALUES ('6851', 'Janderup Vestj');
INSERT INTO zipcodes VALUES ('6852', 'Billum');
INSERT INTO zipcodes VALUES ('6853', 'Vejers Strand');
INSERT INTO zipcodes VALUES ('6854', 'Henne');
INSERT INTO zipcodes VALUES ('6855', 'Outrup');
INSERT INTO zipcodes VALUES ('6857', 'Blåvand');
INSERT INTO zipcodes VALUES ('6862', 'Tistrup');
INSERT INTO zipcodes VALUES ('6870', 'Ølgod');
INSERT INTO zipcodes VALUES ('6880', 'Tarm');
INSERT INTO zipcodes VALUES ('6893', 'Hemmet');
INSERT INTO zipcodes VALUES ('6900', 'Skjern');
INSERT INTO zipcodes VALUES ('6920', 'Videbæk');
INSERT INTO zipcodes VALUES ('6933', 'Kibæk');
INSERT INTO zipcodes VALUES ('6940', 'Lem St');
INSERT INTO zipcodes VALUES ('6950', 'Ringkøbing');
INSERT INTO zipcodes VALUES ('6960', 'Hvide Sande');
INSERT INTO zipcodes VALUES ('6971', 'Spjald');
INSERT INTO zipcodes VALUES ('6973', 'Ørnhøj');
INSERT INTO zipcodes VALUES ('6980', 'Tim');
INSERT INTO zipcodes VALUES ('6990', 'Ulfborg');
INSERT INTO zipcodes VALUES ('7000', 'Fredericia');
INSERT INTO zipcodes VALUES ('7007', 'Fredericia');
INSERT INTO zipcodes VALUES ('7029', 'Fredericia');
INSERT INTO zipcodes VALUES ('7080', 'Børkop');
INSERT INTO zipcodes VALUES ('7100', 'Vejle');
INSERT INTO zipcodes VALUES ('7120', 'Vejle Øst');
INSERT INTO zipcodes VALUES ('7130', 'Juelsminde');
INSERT INTO zipcodes VALUES ('7140', 'Stouby');
INSERT INTO zipcodes VALUES ('7150', 'Barrit');
INSERT INTO zipcodes VALUES ('7160', 'Tørring');
INSERT INTO zipcodes VALUES ('7171', 'Uldum');
INSERT INTO zipcodes VALUES ('7173', 'Vonge');
INSERT INTO zipcodes VALUES ('7182', 'Bredsten');
INSERT INTO zipcodes VALUES ('7183', 'Randbøl');
INSERT INTO zipcodes VALUES ('7184', 'Vandel');
INSERT INTO zipcodes VALUES ('7190', 'Billund');
INSERT INTO zipcodes VALUES ('7200', 'Grindsted');
INSERT INTO zipcodes VALUES ('7250', 'Hejnsvig');
INSERT INTO zipcodes VALUES ('7260', 'Sønder Omme');
INSERT INTO zipcodes VALUES ('7270', 'Stakroge');
INSERT INTO zipcodes VALUES ('7280', 'Sønder Felding');
INSERT INTO zipcodes VALUES ('7300', 'Jelling');
INSERT INTO zipcodes VALUES ('7321', 'Gadbjerg');
INSERT INTO zipcodes VALUES ('7323', 'Give');
INSERT INTO zipcodes VALUES ('7330', 'Brande');
INSERT INTO zipcodes VALUES ('7361', 'Ejstrupholm');
INSERT INTO zipcodes VALUES ('7362', 'Hampen');
INSERT INTO zipcodes VALUES ('7400', 'Herning');
INSERT INTO zipcodes VALUES ('7401', 'Herning');
INSERT INTO zipcodes VALUES ('7429', 'Herning');
INSERT INTO zipcodes VALUES ('7430', 'Ikast');
INSERT INTO zipcodes VALUES ('7441', 'Bording');
INSERT INTO zipcodes VALUES ('7442', 'Engesvang');
INSERT INTO zipcodes VALUES ('7451', 'Sunds');
INSERT INTO zipcodes VALUES ('7470', 'Karup J');
INSERT INTO zipcodes VALUES ('7480', 'Vildbjerg');
INSERT INTO zipcodes VALUES ('7490', 'Aulum');
INSERT INTO zipcodes VALUES ('7500', 'Holstebro');
INSERT INTO zipcodes VALUES ('7540', 'Haderup');
INSERT INTO zipcodes VALUES ('7550', 'Sørvad');
INSERT INTO zipcodes VALUES ('7560', 'Hjerm');
INSERT INTO zipcodes VALUES ('7570', 'Vemb');
INSERT INTO zipcodes VALUES ('7600', 'Struer');
INSERT INTO zipcodes VALUES ('7620', 'Lemvig');
INSERT INTO zipcodes VALUES ('7650', 'Bøvlingbjerg');
INSERT INTO zipcodes VALUES ('7660', 'Bækmarksbro');
INSERT INTO zipcodes VALUES ('7673', 'Harboøre');
INSERT INTO zipcodes VALUES ('7680', 'Thyborøn');
INSERT INTO zipcodes VALUES ('7700', 'Thisted');
INSERT INTO zipcodes VALUES ('7730', 'Hanstholm');
INSERT INTO zipcodes VALUES ('7741', 'Frøstrup');
INSERT INTO zipcodes VALUES ('7742', 'Vesløs');
INSERT INTO zipcodes VALUES ('7752', 'Snedsted');
INSERT INTO zipcodes VALUES ('7755', 'Bedsted Thy');
INSERT INTO zipcodes VALUES ('7760', 'Hurup Thy');
INSERT INTO zipcodes VALUES ('7770', 'Vestervig');
INSERT INTO zipcodes VALUES ('7790', 'Thyholm');
INSERT INTO zipcodes VALUES ('7800', 'Skive');
INSERT INTO zipcodes VALUES ('7830', 'Vinderup');
INSERT INTO zipcodes VALUES ('7840', 'Højslev');
INSERT INTO zipcodes VALUES ('7850', 'Stoholm Jyll');
INSERT INTO zipcodes VALUES ('7860', 'Spøttrup');
INSERT INTO zipcodes VALUES ('7870', 'Roslev');
INSERT INTO zipcodes VALUES ('7884', 'Fur');
INSERT INTO zipcodes VALUES ('7900', 'Nykøbing M');
INSERT INTO zipcodes VALUES ('7950', 'Erslev');
INSERT INTO zipcodes VALUES ('7960', 'Karby');
INSERT INTO zipcodes VALUES ('7970', 'Redsted M');
INSERT INTO zipcodes VALUES ('7980', 'Vils');
INSERT INTO zipcodes VALUES ('7990', 'Øster Assels');
INSERT INTO zipcodes VALUES ('8000', 'Århus C');
INSERT INTO zipcodes VALUES ('8011', 'Århus C');
INSERT INTO zipcodes VALUES ('8100', 'Århus C');
INSERT INTO zipcodes VALUES ('8200', 'Århus N');
INSERT INTO zipcodes VALUES ('8210', 'Århus V');
INSERT INTO zipcodes VALUES ('8220', 'Brabrand');
INSERT INTO zipcodes VALUES ('8229', 'Risskov Ø');
INSERT INTO zipcodes VALUES ('8230', 'Åbyhøj');
INSERT INTO zipcodes VALUES ('8240', 'Risskov');
INSERT INTO zipcodes VALUES ('8245', 'Risskov Ø');
INSERT INTO zipcodes VALUES ('8250', 'Egå');
INSERT INTO zipcodes VALUES ('8260', 'Viby J');
INSERT INTO zipcodes VALUES ('8270', 'Højbjerg');
INSERT INTO zipcodes VALUES ('8300', 'Odder');
INSERT INTO zipcodes VALUES ('8305', 'Samsø');
INSERT INTO zipcodes VALUES ('8310', 'Tranbjerg J');
INSERT INTO zipcodes VALUES ('8320', 'Mårslet');
INSERT INTO zipcodes VALUES ('8330', 'Beder');
INSERT INTO zipcodes VALUES ('8340', 'Malling');
INSERT INTO zipcodes VALUES ('8350', 'Hundslund');
INSERT INTO zipcodes VALUES ('8355', 'Solbjerg');
INSERT INTO zipcodes VALUES ('8361', 'Hasselager');
INSERT INTO zipcodes VALUES ('8362', 'Hørning');
INSERT INTO zipcodes VALUES ('8370', 'Hadsten');
INSERT INTO zipcodes VALUES ('8380', 'Trige');
INSERT INTO zipcodes VALUES ('8381', 'Tilst');
INSERT INTO zipcodes VALUES ('8382', 'Hinnerup');
INSERT INTO zipcodes VALUES ('8400', 'Ebeltoft');
INSERT INTO zipcodes VALUES ('8410', 'Rønde');
INSERT INTO zipcodes VALUES ('8420', 'Knebel');
INSERT INTO zipcodes VALUES ('8444', 'Balle');
INSERT INTO zipcodes VALUES ('8450', 'Hammel');
INSERT INTO zipcodes VALUES ('8462', 'Harlev J');
INSERT INTO zipcodes VALUES ('8464', 'Galten');
INSERT INTO zipcodes VALUES ('8471', 'Sabro');
INSERT INTO zipcodes VALUES ('8472', 'Sporup');
INSERT INTO zipcodes VALUES ('8500', 'Grenaa');
INSERT INTO zipcodes VALUES ('8520', 'Lystrup');
INSERT INTO zipcodes VALUES ('8530', 'Hjortshøj');
INSERT INTO zipcodes VALUES ('8541', 'Skødstrup');
INSERT INTO zipcodes VALUES ('8543', 'Hornslet');
INSERT INTO zipcodes VALUES ('8544', 'Mørke');
INSERT INTO zipcodes VALUES ('8550', 'Ryomgård');
INSERT INTO zipcodes VALUES ('8560', 'Kolind');
INSERT INTO zipcodes VALUES ('8570', 'Trustrup');
INSERT INTO zipcodes VALUES ('8581', 'Nimtofte');
INSERT INTO zipcodes VALUES ('8585', 'Glesborg');
INSERT INTO zipcodes VALUES ('8586', 'Ørum Djurs');
INSERT INTO zipcodes VALUES ('8592', 'Anholt');
INSERT INTO zipcodes VALUES ('8600', 'Silkeborg');
INSERT INTO zipcodes VALUES ('8620', 'Kjellerup');
INSERT INTO zipcodes VALUES ('8632', 'Lemming');
INSERT INTO zipcodes VALUES ('8641', 'Sorring');
INSERT INTO zipcodes VALUES ('8643', 'Ans By');
INSERT INTO zipcodes VALUES ('8653', 'Them');
INSERT INTO zipcodes VALUES ('8654', 'Bryrup');
INSERT INTO zipcodes VALUES ('8660', 'Skanderborg');
INSERT INTO zipcodes VALUES ('8670', 'Låsby');
INSERT INTO zipcodes VALUES ('8680', 'Ry');
INSERT INTO zipcodes VALUES ('8700', 'Horsens');
INSERT INTO zipcodes VALUES ('8721', 'Daugård');
INSERT INTO zipcodes VALUES ('8722', 'Hedensted');
INSERT INTO zipcodes VALUES ('8723', 'Løsning');
INSERT INTO zipcodes VALUES ('8732', 'Hovedgård');
INSERT INTO zipcodes VALUES ('8740', 'Brædstrup');
INSERT INTO zipcodes VALUES ('8751', 'Gedved');
INSERT INTO zipcodes VALUES ('8752', 'Østbirk');
INSERT INTO zipcodes VALUES ('8762', 'Flemming');
INSERT INTO zipcodes VALUES ('8763', 'Rask Mølle');
INSERT INTO zipcodes VALUES ('8765', 'Klovborg');
INSERT INTO zipcodes VALUES ('8766', 'Nørre Snede');
INSERT INTO zipcodes VALUES ('8781', 'Stenderup');
INSERT INTO zipcodes VALUES ('8783', 'Hornsyld');
INSERT INTO zipcodes VALUES ('8800', 'Viborg');
INSERT INTO zipcodes VALUES ('8830', 'Tjele');
INSERT INTO zipcodes VALUES ('8831', 'Løgstrup');
INSERT INTO zipcodes VALUES ('8832', 'Skals');
INSERT INTO zipcodes VALUES ('8840', 'Røærsbro');
INSERT INTO zipcodes VALUES ('8850', 'Bjerringbro');
INSERT INTO zipcodes VALUES ('8860', 'Ulstrup');
INSERT INTO zipcodes VALUES ('8870', 'Langå');
INSERT INTO zipcodes VALUES ('8881', 'Thorsø');
INSERT INTO zipcodes VALUES ('8882', 'Fårvang');
INSERT INTO zipcodes VALUES ('8883', 'Gjern');
INSERT INTO zipcodes VALUES ('8900', 'Randers C');
INSERT INTO zipcodes VALUES ('8920', 'Randers NV');
INSERT INTO zipcodes VALUES ('8930', 'Randers NØ');
INSERT INTO zipcodes VALUES ('8940', 'Randers SV');
INSERT INTO zipcodes VALUES ('8950', 'Ørsted');
INSERT INTO zipcodes VALUES ('8960', 'Randers SØ');
INSERT INTO zipcodes VALUES ('8961', 'Allingåbro');
INSERT INTO zipcodes VALUES ('8963', 'Auning');
INSERT INTO zipcodes VALUES ('8970', 'Havndal');
INSERT INTO zipcodes VALUES ('8981', 'Spentrup');
INSERT INTO zipcodes VALUES ('8983', 'Gjerlev J');
INSERT INTO zipcodes VALUES ('8990', 'Fårup');
INSERT INTO zipcodes VALUES ('9000', 'Aalborg');
INSERT INTO zipcodes VALUES ('9020', 'Aalborg');
INSERT INTO zipcodes VALUES ('9029', 'Aalborg');
INSERT INTO zipcodes VALUES ('9100', 'Aalborg');
INSERT INTO zipcodes VALUES ('9200', 'Aalborg SV');
INSERT INTO zipcodes VALUES ('9210', 'Aalborg SØ');
INSERT INTO zipcodes VALUES ('9220', 'Aalborg Øst');
INSERT INTO zipcodes VALUES ('9230', 'Svenstrup J');
INSERT INTO zipcodes VALUES ('9240', 'Nibe');
INSERT INTO zipcodes VALUES ('9260', 'Gistrup');
INSERT INTO zipcodes VALUES ('9270', 'Klarup');
INSERT INTO zipcodes VALUES ('9280', 'Storvorde');
INSERT INTO zipcodes VALUES ('9293', 'Kongerslev');
INSERT INTO zipcodes VALUES ('9300', 'Sæby');
INSERT INTO zipcodes VALUES ('9310', 'Vodskov');
INSERT INTO zipcodes VALUES ('9320', 'Hjallerup');
INSERT INTO zipcodes VALUES ('9330', 'Dronninglund');
INSERT INTO zipcodes VALUES ('9340', 'Asaa');
INSERT INTO zipcodes VALUES ('9352', 'Dybvad');
INSERT INTO zipcodes VALUES ('9362', 'Gandrup');
INSERT INTO zipcodes VALUES ('9370', 'Hals');
INSERT INTO zipcodes VALUES ('9380', 'Vestbjerg');
INSERT INTO zipcodes VALUES ('9381', 'Sulsted');
INSERT INTO zipcodes VALUES ('9382', 'Tylstrup');
INSERT INTO zipcodes VALUES ('9400', 'Nørresundby');
INSERT INTO zipcodes VALUES ('9430', 'Vadum');
INSERT INTO zipcodes VALUES ('9440', 'Aabybro');
INSERT INTO zipcodes VALUES ('9460', 'Brovst');
INSERT INTO zipcodes VALUES ('9480', 'Løkken');
INSERT INTO zipcodes VALUES ('9490', 'Pandrup');
INSERT INTO zipcodes VALUES ('9492', 'Blokhus');
INSERT INTO zipcodes VALUES ('9493', 'Saltum');
INSERT INTO zipcodes VALUES ('9500', 'Hobro');
INSERT INTO zipcodes VALUES ('9510', 'Arden');
INSERT INTO zipcodes VALUES ('9520', 'Skørping');
INSERT INTO zipcodes VALUES ('9530', 'Støvring');
INSERT INTO zipcodes VALUES ('9541', 'Suldrup');
INSERT INTO zipcodes VALUES ('9550', 'Mariager');
INSERT INTO zipcodes VALUES ('9560', 'Hadsund');
INSERT INTO zipcodes VALUES ('9574', 'Bælum');
INSERT INTO zipcodes VALUES ('9575', 'Terndrup');
INSERT INTO zipcodes VALUES ('9600', 'Aars');
INSERT INTO zipcodes VALUES ('9610', 'Nørager');
INSERT INTO zipcodes VALUES ('9620', 'Aalestrup');
INSERT INTO zipcodes VALUES ('9631', 'Gedsted');
INSERT INTO zipcodes VALUES ('9632', 'Møldrup');
INSERT INTO zipcodes VALUES ('9640', 'Farsø');
INSERT INTO zipcodes VALUES ('9670', 'Løgstør');
INSERT INTO zipcodes VALUES ('9681', 'Ranum');
INSERT INTO zipcodes VALUES ('9690', 'Fjerritslev');
INSERT INTO zipcodes VALUES ('9700', 'Brønderslev');
INSERT INTO zipcodes VALUES ('9740', 'Jerslev J');
INSERT INTO zipcodes VALUES ('9750', 'Østervrå');
INSERT INTO zipcodes VALUES ('9760', 'Vrå');
INSERT INTO zipcodes VALUES ('9800', 'Hjørring');
INSERT INTO zipcodes VALUES ('9830', 'Tårs');
INSERT INTO zipcodes VALUES ('9850', 'Hirtshals');
INSERT INTO zipcodes VALUES ('9870', 'Sindal');
INSERT INTO zipcodes VALUES ('9881', 'Bindslev');
INSERT INTO zipcodes VALUES ('9900', 'Frederikshavn');
INSERT INTO zipcodes VALUES ('9940', 'Læsø');
INSERT INTO zipcodes VALUES ('9970', 'Strandby');
INSERT INTO zipcodes VALUES ('9981', 'Jerup');
INSERT INTO zipcodes VALUES ('9982', 'Ålbæk');
INSERT INTO zipcodes VALUES ('9990', 'Skagen');

insert into customers VALUES (1111,'TestPerson1','22334455','gadegade 123','2500','1234');
insert into customers VALUES (1122,'TestPerson2','22332233','gadegade 123','2800','1234');
insert into customers VALUES (2211,'TestPerson4','22334455','gadegade 123','2900','1234');
insert into customers VALUES (2222,'TestPerson3','22332233','gadegade 123','2700','1234');
insert into buildings (cID,bName,bAddress,zip,bParcel,bSize,bFloors,bYear)VALUES (1111,'A422','gade 123','2500',123,40,2,1990);
insert into buildings (cID,bName,bAddress,zip,bParcel,bSize,bFloors,bYear)VALUES (1122,'A423','gade 123','2700',123,40,2,1990);
select * from customers natural join zipcodes;
select * from buildings natural join zipcodes;


